[Variables]

:x----- API Key - Get yours from https://www.weatherapi.com/ -----x:
WeatherAPI=[YOURKEY] 

:x----- Location - Get location value using https://www.latlong.net/ ----x:
Lon=XX.XX
Lat=XX.XX

:x----- C or F -----x:
TempQuery=current.temp_f
DegText="F"

;TempQuery=current.temp_c
;DegText="C"

:x----- Countdown -----x:
Year=2023
Month=9
Day=6
Hour=0
Minute=0
Second=0

:x----- Countdown Prio-----x:
YearP=2023
MonthP=9
DayP=1
HourP=0
MinuteP=0
SecondP=0

ScrollMouseIncrement=0.1
Format=H
Hidden=0
Hidden2=1
TextColor=255,255,255
ButtonColor=250,126,0

:x----- Color Scheme -----x:
BrightText=253,253,253,255
StandardText=172,177,186,255

SFBackground=0,26,50,230
SFBackground2=67,74,86
SFC1=200,35,55
SFC2=224,98,54
SFC3=215,161,97
SFC4=47,76,121
SFC5=215,161,97

Nothing=0,0,0,1

:x----- Fonts-----x:
;SFF1=NBArchitekt-Regular
SFF1=ProFontWindows

:x----- Time of Day -----x:
TimeOfDay="00":"Good Night","01":"Good Night","02":"Good Night","03":"Good Night","04":"Good Night","05":"Good Night","06":"Good Night","07":"Good Morning","08":"Good Morning","09":"Good Morning","10":"Good Morning","11":"Good Morning","12":"Good Afternoon","13":"Good Afternoon","14":"Good Afternoon","15":"Good Afternoon","16":"Good Afternoon","17":"Good Afternoon","18":"Good Evening","19":"Good Evening","20":"Good Evening","21":"Good Evening","22":"Good Evening","23":"Good Evening"

:x----- Apps & Paths -----x:
App1=X-b0
App1Path=C:\Users\blake\OneDrive\Desktop\Xbox.lnk

App2=Dc
App2Path=C:\Users\blake\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk

App3=H20
App3Path=C:\Program Files (x86)\Steam\steam.exe

App4=D-el
App4Path=C:\Program Files (x86)\Steam\steamapps\common\Disco Elysium\disco.exe

App5=Ds
App5Path=C:\XboxGames\Death Stranding\Content\NIP.Win64.Submission.DX12.Opt.GDK.exe